import { useState } from "react";
import { API } from "./Chat";
import { Copy } from "./i18n";
type Session={id:string;created:string;updated:string;status:string;submitted:boolean;lead:Record<string,string>;messages:{role:string;text:string;ts:string}[]};
export function Admin({t}:{t:Copy}){
 const [token,setToken]=useState(""),[items,setItems]=useState<Session[]>([]),[selected,setSelected]=useState<Session|null>(null),[error,setError]=useState(""),[filter,setFilter]=useState(""),[offset,setOffset]=useState(0);
 async function load(next=0){setError("");try{const r=await fetch(API+"/sessions?limit=100&offset="+next,{headers:{Authorization:"Bearer "+token}});if(!r.ok)throw Error("Нет доступа. Проверьте ключ и доступность сервера.");setItems((await r.json()).sessions);setOffset(next)}catch(e){setError(String(e))}}
 async function change(status:string){if(!selected)return;const r=await fetch(API+"/sessions/"+selected.id,{method:"PATCH",headers:{Authorization:"Bearer "+token,"Content-Type":"application/json"},body:JSON.stringify({status})});if(r.ok){setSelected({...selected,status});void load(offset)}else setError("Не удалось сохранить")}
 function exportData(){const b=new Blob([JSON.stringify(selected??items,null,2)],{type:"application/json"});const url=URL.createObjectURL(b);const a=document.createElement("a");a.href=url;a.download="mastercheb-leads.json";a.click();URL.revokeObjectURL(url)}
 async function remove(){if(!selected||!confirm("Удалить этот диалог и заявку без возможности восстановления?"))return;const r=await fetch(API+"/sessions/"+selected.id,{method:"DELETE",headers:{Authorization:"Bearer "+token}});if(r.ok){setSelected(null);void load(offset)}else setError("Не удалось удалить")}
 return <main className="admin"><a href="/">← МастерЧеб</a><h1>{t.admin}</h1><p>Личный кабинет Александра. Ключ хранится только в памяти этой страницы.</p><form className="admin-toolbar" onSubmit={e=>{e.preventDefault();void load()}}><input type="password" aria-label="Ключ доступа" placeholder="Ключ доступа из .env" value={token} onChange={e=>setToken(e.target.value)} autoComplete="off"/><button className="button primary">Открыть / обновить</button><button type="button" className="button outline" onClick={()=>{setToken("");setItems([]);setSelected(null)}}>Выйти</button></form>{error&&<p role="alert">{error}</p>}<div className="admin-toolbar"><input aria-label="Поиск" placeholder="Поиск на странице" value={filter} onChange={e=>setFilter(e.target.value)}/><button className="button outline" onClick={exportData}>Экспорт JSON</button><button disabled={!offset} onClick={()=>void load(Math.max(0,offset-100))}>←</button><span>{offset+1}–{offset+items.length}</span><button disabled={items.length<100} onClick={()=>void load(offset+100)}>→</button></div><div className="admin-grid"><div className="admin-list">{items.filter(s=>JSON.stringify(s.lead).toLowerCase().includes(filter.toLowerCase())).map(s=><button className={selected?.id===s.id?"selected":""} key={s.id} onClick={()=>setSelected(s)}><strong>{s.lead.name||"Посетитель"} · {s.lead.company||"—"}</strong><small>{new Date(s.updated).toLocaleString()} · {s.submitted?"Заявка":"Диалог"} · {s.status}</small></button>)}</div>{selected&&<article className="admin-detail"><h2>{selected.lead.name||"Диалог"}</h2><div className="admin-toolbar"><select aria-label="Статус" value={selected.status} onChange={e=>void change(e.target.value)}><option value="new">Новая</option><option value="contacted">Связался</option><option value="completed">Завершено</option></select><button onClick={()=>void remove()}>Удалить данные</button></div><dl>{Object.entries(selected.lead).map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v}</dd></div>)}</dl>{selected.messages.map((m,i)=><div className="admin-message" key={i}><strong>{m.role==="assistant"?"Маша":"Посетитель"} · {new Date(m.ts).toLocaleTimeString()}</strong><p>{m.text}</p></div>)}</article>}</div></main>
}