import { useEffect, useState } from "react";
import { ArrowDown, ArrowUpRight, Check, MessageCircle, Mic, Sparkles, Play, ShieldCheck, Layers, X } from "lucide-react";
import { copy, Lang } from "./i18n";
import { Chat, ContactLinks, API } from "./Chat";
import { Admin } from "./Admin";
import { Privacy } from "./Privacy";
export function App(){
 const params=new URLSearchParams(location.search),initial=params.get("lang")??"ru";
 const [lang,setLang]=useState<Lang>(["ru","en","zh"].includes(initial)?initial as Lang:"ru"),[online,setOnline]=useState<boolean|null>(null),[voiceReady,setVoiceReady]=useState(false);
 const variant=["1","2","3"].includes(params.get("variant")??"")?Number(params.get("variant")):2,t=copy[lang];
 const [prepared,setPrepared]=useState(""),[copied,setCopied]=useState(false),[formConsent,setFormConsent]=useState(false);
 useEffect(()=>{document.documentElement.lang=lang==="zh"?"zh-CN":lang;const u=new URL(location.href);if(lang==="ru")u.searchParams.delete("lang");else u.searchParams.set("lang",lang);history.replaceState(null,"",u);setPrepared("")},[lang]);
 useEffect(()=>{let disposed=false;let controller:AbortController;async function check(){controller=new AbortController();const id=setTimeout(()=>controller.abort(),3500);try{const r=await fetch(API+"/health",{signal:controller.signal,cache:"no-store"});const d=await r.json();if(!disposed){setOnline(r.ok&&d.text&&d.capacity_available);setVoiceReady(!!d.voice)}}catch{if(!disposed){setOnline(false);setVoiceReady(false)}}finally{clearTimeout(id)}}void check();const id=setInterval(check,20000);return()=>{disposed=true;controller?.abort();clearInterval(id)}},[]);
 function prepare(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const data=new FormData(e.currentTarget);setPrepared(t.requestTitle+" — MasterCheb\n"+t.labels.map((l,i)=>l+": "+data.get(String(i))).join("\n"));setCopied(false)}
 if(params.get("page")==="admin")return <Admin t={t}/>;
 if(params.get("page")==="privacy")return <Privacy lang={lang}/>;
 return <div className={"site variant-"+variant}>
 <a href="#demo" className="skip-link">{t.try}</a>
 <header className="header container"><a className="brand" href="/"><span className="brand-mark"><svg viewBox="0 0 30 30"><path d="M5 21V10l10 8 10-8v11"/></svg></span>{t.brand}<span className="brand-dot">.</span></a><nav>{t.nav.map((label,i)=><a key={label} href={["#how","#capabilities","#pricing","#founder"][i]}>{label}</a>)}</nav><div className="header-right"><select aria-label="Language / Язык / 语言" value={lang} onChange={e=>setLang(e.target.value as Lang)}><option value="ru">RU</option><option value="en">EN</option><option value="zh">中文</option></select><a className="button compact outline" href="#contact">{t.consult}<ArrowUpRight size={15}/></a></div></header>
 <main>
 <section className="hero container"><div className="hero-copy"><div className="eyebrow"><span className="live-dot"/>{t.badge}</div><h1>{variant===2?t.variant2:variant===3?t.variant3:t.hero}<span>{t.accent}</span></h1><p className="hero-intro">{t.intro}</p><div className="hero-buttons"><a className="button primary" href="#demo"><Mic size={19}/>{t.try}<ArrowUpRight size={18}/></a><a className="text-link" href="#how">{t.explore}<ArrowDown size={16}/></a></div><small className="hero-note">{t.note}</small></div>
 <div className="hero-art"><div className="art-grid"/><div className="floating-label top"><span className="live-dot"/>{t.masha} · AI</div><div className="orb"><span/></div><div className="waveform">{Array.from({length:35},(_,i)=><i key={i} style={{height:(12+Math.sin(i*.63)**2*45)+"px",animationDelay:(i*.07)+"s"}}/>)}</div><div className="floating-message first"><MessageCircle size={18}/>{t.questionChips[0]}</div><div className="floating-message second"><Check size={18}/>{t.capabilities[0][0]}<span>↗</span></div><div className="art-caption"><span>01 /</span> {t.role}</div></div></section>
 <div className="proof-strip container">{t.metrics.map((m,i)=><div key={m}>{i===0?<Sparkles size={18}/>:i===1?<MessageCircle size={18}/>:<ShieldCheck size={18}/>}<span>{m}</span></div>)}</div>
 <section id="how" className="section container how-section"><div className="section-heading"><div><span className="eyebrow">{t.howTag}</span><h2>{t.howTitle}</h2></div><p>{t.howIntro}</p></div><div className="steps">{t.steps.map(([title,body],i)=><article key={title}><span className="step-no">0{i+1}</span><div className="step-line"/><h3>{title}</h3><p>{body}</p></article>)}</div></section>
 <section id="demo" className="demo-section"><div className="container demo-grid"><div className="demo-copy"><span className="eyebrow">{t.demoLabel}</span><h2>{t.demoTitle}</h2><p>{t.demoIntro}</p><div className="demo-modes"><span><Mic size={17}/>{t.voice}</span><span><MessageCircle size={17}/>{t.typing}</span><span><VolumeIcon/>{t.sound}</span></div><div className="mini-note"><ShieldCheck size={20}/><p>{lang==="ru"?"Аудио не сохраняется. Текст разговора помогает продолжить консультацию.":lang==="en"?"Audio is not saved. Conversation text helps with your consultation.":"不保存录音，对话文字用于后续咨询。"}</p></div></div><Chat key={lang} lang={lang} t={t} online={online} voiceReady={voiceReady}/></div></section>
 <section id="capabilities" className="section container"><span className="eyebrow">{t.capabilityTag}</span><h2>{t.capabilityTitle}</h2><div className="capabilities">{t.capabilities.map(([title,body],i)=><article key={title}><span className="icon-box">{[<MessageCircle/>,<ArrowUpRight/>,<Mic/>,<Layers/>][i]}</span><h3>{title}</h3><p>{body}</p></article>)}</div><p className="muted-note">{t.customNote}</p></section>
 <section id="pricing" className="section pricing-section"><div className="container"><span className="eyebrow">{t.pricingTag}</span><h2>{t.pricingTitle}</h2><div className="pricing-grid">{[0,1].map(i=><article className={"price-card "+(!i?"featured":"")} key={i}><div className="price-top"><span>{i?"02":"01"}</span>{!i&&<span className="tag">{t.recommended}</span>}</div><h3>{i?t.onprem:t.subscription}</h3><p>{i?t.onpremDesc:t.subDesc}</p><div className="price"><small>{t.from}</small><strong>{i?"250 000":"50 000"} <span>₽</span></strong><small>{i?t.once:t.monthly}</small></div><ul>{(i?t.onpremItems:t.subItems).map(s=><li key={s}><Check size={17}/>{s}</li>)}</ul><a href="#contact" className={"button "+(i?"outline":"primary")}>{t.consult}<ArrowUpRight size={17}/></a></article>)}</div><p className="muted-note">{t.priceNote}</p><div className="free-demo"><div><h3>{t.demoFree}</h3><p>{t.demoFreeText}</p></div><a className="button outline" href="#contact">{t.lead}<ArrowUpRight size={17}/></a></div></div></section>
 <section id="work" className="section container"><div className="section-heading"><div><span className="eyebrow">{t.workTag}</span><h2>{t.workTitle}</h2></div><p>{t.workIntro}</p></div><div className="videos">{t.videos.map((v,i)=><article key={v}><div className={"video-cover cover-"+i}><span className="video-number">0{i+1}</span><Play size={28}/><small>{t.video}</small></div><h3>{v}</h3></article>)}</div></section>
 <section id="founder" className="section container founder-section"><div className="founder-portrait"><span className="monogram">AM<span>✳</span></span><div><strong>{t.founder}</strong><small>{t.founderRole}</small></div></div><div className="founder-copy"><span className="eyebrow">{t.founderTag}</span><h2>{t.founder}</h2><p>{t.founderText}</p><blockquote>{t.founderQuote}</blockquote><a href="#contact" className="text-link">{t.consult}<ArrowUpRight size={18}/></a></div></section>
 <section className="section container faq-section"><h2>{t.faqTitle}</h2><div>{t.faq.map(([q,a])=><details key={q}><summary>{q}<span>+</span></summary><p>{a}</p></details>)}</div></section>
 <section id="contact" className="contact-section"><div className="container contact-simple"><div><span className="eyebrow">LET’S TALK</span><h2>{t.contactTitle}</h2><p>{t.contactIntro}</p><ContactLinks t={t}/><div className="direct-contacts"><a href="https://t.me/mastercheb">@MasterCheb</a><a href="tel:+79176693889">+7 917 669-38-89</a><a href="mailto:pochtaeto@gmail.com">pochtaeto@gmail.com</a></div></div></div></section>
 </main><footer className="container footer"><div><a className="brand" href="/">{t.brand}<span className="brand-dot">.</span></a><p>{t.footer}</p></div><div><a href={"?page=privacy&lang="+lang}>{t.policy}</a><p>{t.rights}</p><small>© 2026 MasterCheb</small></div></footer>
 {params.has("variant")&&<aside className="variant-picker" aria-label={t.variantPicker}>{t.variants.map((v,i)=><a className={variant===i+1?"selected":""} key={v} href={"?variant="+(i+1)+"&lang="+lang}>{i+1}. {v}</a>)}<a href="/" title="Close"><X size={16}/></a></aside>}
 </div>
}
function VolumeIcon(){return <span aria-hidden="true">◖))</span>}
